services:
  # Bases de datos a la cual me conectaré desde mi proyecto
  userdb:
    image: postgres:15
    container_name: usermicroservice.db
    restart: always
    environment:
      POSTGRES_DB: usersDb
      POSTGRES_USER: adminuser
      POSTGRES_PASSWORD: adminuser123
    ports:
      - "5435:5432"
    volumes:
      - ./postgres_data_users:/var/lib/postgresql/data/
      - ./init-scripts/userdb-init.sql:/docker-entrypoint-initdb.d/userdb-init.sql

  taskdb:
    image: postgres:15
    container_name: taskmicroservice.db
    restart: always
    environment:
      POSTGRES_DB: tasksDb
      POSTGRES_USER: admintask
      POSTGRES_PASSWORD: admintask123
    ports:
      - "5436:5432"
    volumes:
      - ./postgres_data_tasks:/var/lib/postgresql/data/
      - ./init-scripts/taskdb-init.sql:/docker-entrypoint-initdb.d/taskdb-init.sql

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq.taskbroker
    ports:
      - "5672:5672"
      - "15672:15672"  # web de administración
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: 123


  # cliente de base de datos si es que no quiero usar la linea de comandos
  db_client:
    image: dpage/pgadmin4
    container_name: taskapp.db.cliente
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - ./pgadmin_data:/var/lib/pgadmin
    ports:
      - "80:80"

volumes:
  postgres_data: