version: '3.4'

services:
  # Bases de datos a la cual me conectaré desde mi proyecto
  userdb:
    image: postgres
    container_name: usermicroservice.db
    restart: always
    environment:
      POSTGRES_DB: usersDb
      POSTGRES_USER: adminuser
      POSTGRES_PASSWORD: adminuser123
    ports:
      - "5435:5432"
    volumes:
      - ./postgres_data_users:/var/lib/postgresql/data/

  taskdb:
    image: postgres
    container_name: taskmicroservice.db
    restart: always
    environment:
      POSTGRES_DB: tasksDb
      POSTGRES_USER: admintask
      POSTGRES_PASSWORD: admintask123
    ports:
      - "5436:5432"
    volumes:
      - ./postgres_data_tasks:/var/lib/postgresql/data/


  # cliente de base de datos si es que no quiero usar la linea de comandos
  db_client:
    image: dpage/pgadmin4
    container_name: taskapp.db.cliente
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - ./pgadmin_data:/var/lib/pgadmin
    ports:
      - "80:80"

volumes:
  postgres_data: