global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'user-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8091'] # o el puerto expuesto del contenedor

#  - job_name: 'task-service'
#    metrics_path: '/actuator/prometheus'
#    static_configs:
#      - targets: ['host.docker.internal:8082']