server:
  port: 8093

spring:
  application:
    name: microservice-notification
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: 123


jpa:
  show-sql: true

# configuración para la documentación swagger
#springdoc:
#  api-docs:
#    path: /openapi.json
#  swagger-ui:
#    path: /docs
#    url: /openapi.json