spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: 123
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: c3f115a4db5ce2
    password: 9e5fe29f0072ee