server:
  port: 8092

spring:
  application:
    name: microservice-tasks
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  # configuraci贸n para la conexi贸n con rabbitmq
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: 123

jpa:
  show-sql: true


resilience4j:
  circuitbreaker:
    configs:
      default:
        failure-rate-threshold: 50
        sliding-window-type: count_based
        sliding-window-size: 10

        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 1

        register-health-indicator: false
        record-exceptions:
          - io.netty.handler.timeout.ReadTimeoutException
          - java.lang.RuntimeException
          - java.lang.Exception
    instances:
      api-catalog:
        base-config: default

  ratelimiter:
    configs:
      default:
        limit-for-period: 2
        limit-refresh-period: 3s
        timeout-duration: 1s
    instances:
      post-reservation:
        base-config: default

# configuraci贸n para la documentaci贸n swagger
springdoc:
  api-docs:
    path: /openapi.json
  swagger-ui:
    path: /docs
    url: /openapi.json