server:
  port: 8092
spring:
  application:
    name: microservice-tasks
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5436/tasksDb
    username: admintask
    password: admintask123
  jpa:
    #database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true


http-connector:
  hosts:
    api-users:
      host: localhost
      port: 8091
      endpoints:
        get-user:
          url: "/api/v1/user/{userId}"
          readTimeout: 1000
          writeTimeout: 1000
          connectionTimeout: 2000



resilience4j:
  circuitbreaker:
    configs:
      default:
        failure-rate-threshold: 50
        sliding-window-type: count_based
        sliding-window-size: 5

        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 1

        register-health-indicator: false
        record-exceptions:
          - io.netty.handler.timeout.ReadTimeoutException
          - java.lang.RuntimeException
          - java.lang.Exception
    instances:
      api-catalog:
        base-config: default

  ratelimiter:
    configs:
      default:
        limit-for-period: 2
        limit-refresh-period: 3s
        timeout-duration: 1s
    instances:
      post-reservation:
        base-config: default

# configuración para la documentación swagger
springdoc:
  api-docs:
    path: /openapi.json
  swagger-ui:
    path: /docs
    url: /openapi.json