server:
  port: 8091
spring:
  application:
    name: microservice-users
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5435/usersDb
    username: adminuser
    password: adminuser123
  jpa:
    #database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true