name: UserService CI

on:
  push:
    branches: ["main"]
    paths:
      - 'microservice-users/**'
      - '.github/workflows/userservice-ci.yml'
  pull_request:
    branches: ["main"]
    paths:
      - 'microservice-users/**'


jobs:
  build-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        ports: ['5432:5432']
        env:
          POSTGRES_DB: usersDb
          POSTGRES_USER: adminuser
          POSTGRES_PASSWORD: adminuser123
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

#      - name: Cache de Dependencias de Maven
#        uses: actions/cache@v3
#        with:
#          path: ~/.m2/repository
#          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
#          restore-keys: |
#            ${{ runner.os }}-maven-

      - name: Configurar JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Compilo el proyecto
        run: mvn -f microservice-users/pom.xml clean compile

      - name: Ejecutar pruebas unitarias
        run: mvn -f microservice-users/pom.xml test -P unit-tests